### ISSUE TITLE
[FEATURE]: Created issue regarding coreui-storybook

### ISSUE THREAD

**Issue by leovigna** [ampProjects/coreui-storybook#1]
Hello, I recently created an issue on the main CoreUI React Admin page regarding creating a React CoreUI storybook. Please let me know if you'd be interested in developing this project and collaborating.

https://github.com/coreui/coreui-free-react-admin-template/issues/217

**Comment by ampProjects** [comment]
Hello @leovigna,
I started to work in this project months ago. That was a initial state but I stopped the project, because I needed a lot of time. As core-ui is based on reactstrap and reactstrap is based on bootstrap, I needed to check every css class for creating all stories with Styled Components. I use React andI thought that Styled Componets it is the best option.

Being honest it is a interesting project, for that reason I started with it. I have used coreui in some personal project and I thingk it is a good framework, but it would be helpful if we could have all components in Storybook.

I would like to finish the project, so I am very interesting in collaborate. Work with Storybook give you more control on the components.

**Comment by leovigna** [comment]
Since CoreUI is launching v3 (which doesn't use reactstrap), I've decided we might as well have the Storybook use CoreUI v3. I have started a repo with Typography, Colors, Buttons, Tables, ListGroup stories. 
Repo: https://github.com/vulcanlink/coreui-react-storybook
Deployment: https://vulcanlink.github.io/coreui-react-storybook/

**Comment by leovigna** [comment]
Closing this issue as was more for discussion purpose.
